Test/access opportunity tests
sertao-dev/mapas-culturais-tests pull request #27
Opened 2024-02-27 17:15 UTC by saracamilodev

Teste do input para acessar alguma das oportunidades.

2024-02-27 17:15 UTC, saracamilodev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Criar cenários de teste para a página de detalhes da Oportunidade](https://trello.com/c/WIVM9M1p/29-criar-cen%C3%A1rios-de-teste-para-a-p%C3%A1gina-de-detalhes-da-oportunidade)

2024-02-27 21:02 UTC, alessandrofeitoza requested changes
Tem alguns arquivos desnecessários, acho que vc executou o comando do cypress fora do diretorio raiz do projeto

2024-02-27 21:57 UTC, Akellymourab approved these changes

2024-02-28 17:46 UTC, alessandrofeitoza approved these changes

2024-02-28 17:47 UTC, alessandrofeitoza commented on cypress/e2e/opportunityPage/index.cy.js
> +    cy.visit("https://redesign.testes.map.as/oportunidade/298/#info");
vc pode estar usando apenas `cy.visit("/oportunidade/298/#info");`

2024-03-04 18:09 UTC, merged